# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='headline',
            field=models.CharField(blank=True, default='Student', max_length=200),
        ),
    ]
